Install the alpha version of zookeeper

diff --git a/install-php-extensions b/install-php-extensions
--- a/install-php-extensions
+++ b/install-php-extensions
@@ -2199,16 +2199,32 @@ installRemoteModule() {
 			fi
 			;;
 		zookeeper)
+			if test -z "$installRemoteModule_version"; then
+				if test $PHP_MAJMIN_VERSION -le 506; then
+					installRemoteModule_version=0.5.0
+				else
+					installRemoteModule_version=1.0.0
+				fi
+			fi
 			case "$DISTRO" in
 				alpine)
 					if ! test -f /usr/local/include/zookeeper/zookeeper.h; then
-						installRemoteModule_tmp="$(curl -sSLf https://downloads.apache.org/zookeeper/stable | sed -E 's/["<>]/\n/g' | grep -E '^(apache-)?zookeeper-[0-9]+\.[0-9]+\.[0-9]+\.(tar\.gz|tgz)$' | head -n1)"
-						if test -z "$installRemoteModule_tmp"; then
-							echo 'Failed to detect the zookeeper library URL' >&2
-							exit 1
+						if test $(compareVersions "$installRemoteModule_version" 1.0.0) -lt 0; then
+							installRemoteModule_src="$(getPackageSource http://archive.apache.org/dist/zookeeper/zookeeper-3.5.9/apache-zookeeper-3.5.9.tar.gz)"
+						else
+							installRemoteModule_tmp="$(curl -sSLf https://downloads.apache.org/zookeeper/stable | sed -E 's/["<>]/\n/g' | grep -E '^(apache-)?zookeeper-[0-9]+\.[0-9]+\.[0-9]+\.(tar\.gz|tgz)$' | head -n1)"
+							if test -z "$installRemoteModule_tmp"; then
+								echo 'Failed to detect the zookeeper library URL' >&2
+								exit 1
+							fi
+							installRemoteModule_src="$(getPackageSource https://downloads.apache.org/zookeeper/stable/$installRemoteModule_tmp)"
 						fi
-						installRemoteModule_src="$(getPackageSource https://downloads.apache.org/zookeeper/stable/$installRemoteModule_tmp)"
 						cd -- "$installRemoteModule_src"
+						if test -d ~/.m2; then
+							installRemoteModule_delm2=n
+						else
+							installRemoteModule_delm2=y
+						fi
 						mvn -pl zookeeper-jute compile
 						cd - >/dev/null
 						cd -- "$installRemoteModule_src/zookeeper-client/zookeeper-client-c"
@@ -2217,16 +2233,12 @@ installRemoteModule() {
 						make -j$(getProcessorCount) CFLAGS='-Wno-stringop-truncation -Wno-format-overflow'
 						make install
 						cd - >/dev/null
+						if test $installRemoteModule_delm2 = y; then
+							rm -rf ~/.m2
+						fi
 					fi
 					;;
 			esac
-			if test -z "$installRemoteModule_version"; then
-				if test $PHP_MAJMIN_VERSION -le 506; then
-					installRemoteModule_version=0.5.0
-				elif test $PHP_MAJMIN_VERSION -ge 703; then
-					installRemoteModule_version=beta
-				fi
-			fi
 			;;
 	esac
 	if test $installRemoteModule_manuallyInstalled -eq 0; then
