Validate the JSON files against their schema, and update PHP-CS-Fixer

diff --git a/scripts/lint b/scripts/lint
--- a/scripts/lint
+++ b/scripts/lint
@@ -36,4 +36,15 @@ elif ! composer run-script lint; then
 	rc=1
 fi
 
+echo '# Checking JSON files'
+if ! composer --version >/dev/null 2>/dev/null; then
+	echo 'Composer is not installed.' >&2
+elif ! test -f ./vendor/autoload.php; then
+	echo 'Composer dependencies are not installed.' >&2
+	rc=1
+elif ! composer run-script check-json-schemas; then
+	echo 'ERROR!' >&2
+	rc=1
+fi
+
 exit $rc
