Accept IPE_SAVE_...DEPS_TO to store required apt/apk dependencies

diff --git a/.github/workflows/test-extensions.yml b/.github/workflows/test-extensions.yml
--- a/.github/workflows/test-extensions.yml
+++ b/.github/workflows/test-extensions.yml
@@ -316,3 +316,76 @@ jobs:
         uses: actions/checkout@v4
       -
         run: docker run --rm --volume "$(pwd):/app" --workdir /app php:8.2-cli-alpine ./scripts/test-icu-data-en-upgradable
+
+  test_persisting_deps:
+    name: Test that IPE_SAVE_...DEPS_TO works
+    needs:
+      - check_syntax_data
+      - check_syntax_shell
+      - check_syntax_php
+    runs-on: ubuntu-latest
+    steps:
+      -
+        name: Checkout
+        uses: actions/checkout@v6
+      -
+        name: Install extensions
+        run: >
+          docker run --rm
+          --volume "$(pwd):/app"
+          --workdir /app
+          --env CI=true
+          --env IPE_SAVE_PERMDEPS_TO=perm-deps.txt
+          --env IPE_SAVE_VOLDEPS_TO=vol-deps.txt
+          php:8.2-cli-alpine
+          ./install-php-extensions zip
+      -
+        name: List permanent deps
+        run: cat perm-deps.txt
+      -
+        name: Check permanent deps
+        run: |
+          search=libzip
+          found=0
+          while read -r line; do
+            set -f
+            set -- $line
+            set +f
+            for dep; do
+              if [ "$dep" = "$search" ]; then
+                found=1
+                break 2
+              fi
+            done
+          done < perm-deps.txt
+          if [ $found -eq 1 ]; then
+            echo 'OK'
+          else
+            echo "$search not found in permanent deps"
+            exit 1
+          fi
+      -
+        name: List volatile deps
+        run: cat vol-deps.txt
+      -
+        name: Check volatile deps
+        run: |
+          search=libzip-dev
+          found=0
+          while read -r line; do
+            set -f
+            set -- $line
+            set +f
+            for dep; do
+              if [ "$dep" = "$search" ]; then
+                found=1
+                break 2
+              fi
+            done
+          done < vol-deps.txt
+          if [ $found -eq 1 ]; then
+            echo 'OK'
+          else
+            echo "$search not found in volatile deps"
+            exit 1
+          fi
